/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttentionPage: typeof import('./src/components/AttentionPage.vue')['default']
    BlogsPage: typeof import('./src/components/BlogsPage.vue')['default']
    CommunityPage: typeof import('./src/components/CommunityPage.vue')['default']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    MyPage: typeof import('./src/components/MyPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
